spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      #password: springCloud_Pwd!
      password: ENC(M4lZVxvedwcA3jCPlbjZG1lXSvLdbmy/7cgEtDluSJxUiIdzDfZyGzh7EJVd5jb1gj6uANWS0BznuPBspqAGCw==)

log:
  app-name: twitter-to-kafka-service

twitter-to-kafka-service:
  enable-mock-tweets: true





